# hugo.toml

baseURL = "https://fossym.github.io/" # IMPORTANT: Change this to your repository's URL
languageCode = "en-us"
title = "FOSS Scouting"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  title = "CogScout"
  description = "Exploring the intersection of Cognitive Science and the Scouting movement"
  author = "Matthew Rennekamp" # Change this
  # author: ["Me", "You"] # multiple authors
  
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false # Enable if you have a comment system
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    # disableHLJS = true # to disable highlight.js
    # disableFingerprinting = true
    favicon = "<link / abs url>"
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    apple_touch_icon = "<link / abs url>"
    safari_pinned_tab = "<link / abs url>"

  [params.label]
    text = "CogScout"
    # icon = "/apple-touch-icon.png"
    # iconHeight = 35

  # profile-mode
  [params.profileMode]
    enabled = true
    title = "CogScout"
    subtitle = "Translating worlds to theories and back."
    imageUrl = "" # You can add a path to an image like "/scout-logo.png" in your static/ folder
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Cognitive Scout Logo"
    buttons = [
        { name = "Articles", url = "/posts" },
        { name = "About", url = "/about" }
    ]

  # social-icons
  [params.socialIcons]
    [params.socialIcons.github]
      url = "https://github.com/mrennekamp" # Change this

# Menu Navigation
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "concepts"
    name = "Core Concepts"
    url = "/concepts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

# For syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
